version: "1"
projects:
- name: sensclassapi
  environments:
  - name: Production
    services:
    - type: web
      name: pythonapi
      runtime: docker
      image:
        url: docker.io/mambodancer/pythonapi:latest
      plan: free
      region: oregon
      autoDeployTrigger: commit