name: Build and Push Docker

on:
  push:
    branches: [ master ]  # Коли пуш в main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v4

      # Логін у Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t mambodancer/pythonapi:latest .

      # Push Docker image
      - name: Push Docker image
        run: docker push mambodancer/pythonapi:latest
